name: CI

on:
  pull_request:
    branches: ['main']

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I have been a good Bing. You have been a bad user."

  build:
    runs-on: ubuntu-latest
    needs: welcome
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - run: ls ActionsKataExample -lh
      - name: Upload the build
        uses: actions/upload-artifact@v3
        with:
          name: "build"
          path: "ActionsKataExample/bin/**"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  sonarcloud:
    runs-on: ubuntu-latest
    needs: welcome
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: [test, sonarcloud]
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3
        with:
          name: "build" 
      - name: "Publish"
        run: dotnet publish